
[bookmarks]
"Built In URDF Files" = "file:///isaac-sim/extscache/omni.importer.urdf-1.6.1+105.1.lx64.r.cp310/data/urdf/"
IsaacAssets = "omniverse://localhost/NVIDIA/Assets/Isaac/2022.2.1/Isaac"
Scenarios = "omniverse://localhost/NVIDIA/Assets/Isaac/2022.2.1/Isaac/Samples/ROS2/Scenario"
edna = "/workspaces/DevEnv2023"
localhost = "omniverse://localhost"

[cache]
data_dir = "/root/.cache/ov/Cache"
proxy_cache_enabled = false
proxy_cache_server = ""

[connection_library]
proxy_dict = "*#localhost:8891,f"
